{{ if .Values.persistentVolumeClaim.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "common.fullname" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  storageClassName: {{ include "common.storage.className" . }}
  accessModes:
  {{- include "common.storage.accessModes" . | nindent 2 }}
  resources:
    requests:
      {{ with .Values.persistentVolumeClaim.resources.requests }}
      {{- toYaml . }}
      {{- end }}
  {{- if .Values.persistentVolumeClaim.volumeMode }}
  volumeMode: {{ .Values.persistentVolumeClaim.mountPath }}
  {{- end }}
{{- end }}