{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "common.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "common.fullname" . }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.autoscaling.cpu }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          {{- if .Values.autoscaling.cpu.averagePercentage }}
          averageUtilization: {{ include "common.averageCpuByPercentage" . }}
          {{- else if .Values.autoscaling.cpu.averageValue }}
          averageValue: {{ include "common.averageCpuValue" . }}
          {{- end }}
    {{- end }}
    {{- if .Values.autoscaling.memory }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          {{- if .Values.autoscaling.memory.averagePercentage }}
          averageUtilization: {{ include "common.averageMemoryByPercentage" . }}
          {{- else if .Values.autoscaling.memory.averageValue }}
          averageValue: {{ include "common.averageMemoryValue" . }}
          {{- end }}
    {{- end }}
{{- end }}
